---
title: "README"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The NewDataAverage is a tidy dataset created from the UCI HAR Dataset. 
The UCI HAR Dataset is a dataset from an experiment called "Human Activity Recognition Using Smartphones Dataset". 
It involved 30 participants, or subjects, (identified in the NewData as ID) and each performed six activities 
(WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING), 
wearing a smartphone, which has an embedded Accelerator and Gyroscope, used to take various measurements (features). 
The total number of measurements taken, for all the participants and all the activities, was 561. 

This original dataset was a group of various tables which were organized in order to be easier to understand and analysed. 
The NewDataAverage has 180 observations of 88 variables. 

The first two columns indicate the participant(subject), 
with an ID variable, which goes from 1 to 30, and an Activity column, which indicates which activity the 
participant was doing when taken the measurment (Walking, Walking_Upstairs, Walking_Downstairs, Sitting, Standing, 
Laying). 

The remaining 86 columns are all averages of 86 different measurements taken by each participant,
doing each activity. 

Therefore, since there are 30 participants doing 6 activities, we have 180 observations (rows). 

These are the variables in NewDataAverage:

 [1] "ID"                                                    
 [2] "Activity"                                              
 [3] "TimeBodyAccelerometer.mean...X"                        
 [4] "TimeBodyAccelerometer.mean...Y"                        
 [5] "TimeBodyAccelerometer.mean...Z"                        
 [6] "TimeGravityAccelerometer.mean...X"                     
 [7] "TimeGravityAccelerometer.mean...Y"                     
 [8] "TimeGravityAccelerometer.mean...Z"                     
 [9] "TimeBodyAccelerometerJerk.mean...X"                    
[10] "TimeBodyAccelerometerJerk.mean...Y"                    
[11] "TimeBodyAccelerometerJerk.mean...Z"                    
[12] "TimeBodyGyroscope.mean...X"                            
[13] "TimeBodyGyroscope.mean...Y"                            
[14] "TimeBodyGyroscope.mean...Z"                            
[15] "TimeBodyGyroscopeJerk.mean...X"                        
[16] "TimeBodyGyroscopeJerk.mean...Y"                        
[17] "TimeBodyGyroscopeJerk.mean...Z"                        
[18] "TimeBodyAccelerometerMagnitude.mean.."                 
[19] "TimeGravityAccelerometerMagnitude.mean.."              
[20] "TimeBodyAccelerometerJerkMagnitude.mean.."             
[21] "TimeBodyGyroscopeMagnitude.mean.."                     
[22] "TimeBodyGyroscopeJerkMagnitude.mean.."                 
[23] "FrequencyBodyAccelerometer.mean...X"                   
[24] "FrequencyBodyAccelerometer.mean...Y"                   
[25] "FrequencyBodyAccelerometer.mean...Z"                   
[26] "FrequencyBodyAccelerometer.meanFreq...X"               
[27] "FrequencyBodyAccelerometer.meanFreq...Y"               
[28] "FrequencyBodyAccelerometer.meanFreq...Z"               
[29] "FrequencyBodyAccelerometerJerk.mean...X"               
[30] "FrequencyBodyAccelerometerJerk.mean...Y"               
[31] "FrequencyBodyAccelerometerJerk.mean...Z"               
[32] "FrequencyBodyAccelerometerJerk.meanFreq...X"           
[33] "FrequencyBodyAccelerometerJerk.meanFreq...Y"           
[34] "FrequencyBodyAccelerometerJerk.meanFreq...Z"           
[35] "FrequencyBodyGyroscope.mean...X"                       
[36] "FrequencyBodyGyroscope.mean...Y"                       
[37] "FrequencyBodyGyroscope.mean...Z"                       
[38] "FrequencyBodyGyroscope.meanFreq...X"                   
[39] "FrequencyBodyGyroscope.meanFreq...Y"                   
[40] "FrequencyBodyGyroscope.meanFreq...Z"                   
[41] "FrequencyBodyAccelerometerMagnitude.mean.."            
[42] "FrequencyBodyAccelerometerMagnitude.meanFreq.."        
[43] "FrequencyBodyBodyAccelerometerJerkMagnitude.mean.."    
[44] "FrequencyBodyBodyAccelerometerJerkMagnitude.meanFreq.."
[45] "FrequencyBodyBodyGyroscopeMagnitude.mean.."            
[46] "FrequencyBodyBodyGyroscopeMagnitude.meanFreq.."        
[47] "FrequencyBodyBodyGyroscopeJerkMagnitude.mean.."        
[48] "FrequencyBodyBodyGyroscopeJerkMagnitude.meanFreq.."    
[49] "angle.tBodyAccelerometerMean.gravity."                 
[50] "angle.tBodyAccelerometerJerkMean..gravityMean."        
[51] "angle.tBodyGyroscopeMean.gravityMean."                 
[52] "angle.tBodyGyroscopeJerkMean.gravityMean."             
[53] "angle.X.gravityMean."                                  
[54] "angle.Y.gravityMean."                                  
[55] "angle.Z.gravityMean."                                  
[56] "TimeBodyAccelerometer.std...X"                         
[57] "TimeBodyAccelerometer.std...Y"                         
[58] "TimeBodyAccelerometer.std...Z"                         
[59] "TimeGravityAccelerometer.std...X"                      
[60] "TimeGravityAccelerometer.std...Y"                      
[61] "TimeGravityAccelerometer.std...Z"                      
[62] "TimeBodyAccelerometerJerk.std...X"                     
[63] "TimeBodyAccelerometerJerk.std...Y"                     
[64] "TimeBodyAccelerometerJerk.std...Z"                     
[65] "TimeBodyGyroscope.std...X"                             
[66] "TimeBodyGyroscope.std...Y"                             
[67] "TimeBodyGyroscope.std...Z"                             
[68] "TimeBodyGyroscopeJerk.std...X"                         
[69] "TimeBodyGyroscopeJerk.std...Y"                         
[70] "TimeBodyGyroscopeJerk.std...Z"                         
[71] "TimeBodyAccelerometerMagnitude.std.."                  
[72] "TimeGravityAccelerometerMagnitude.std.."               
[73] "TimeBodyAccelerometerJerkMagnitude.std.."              
[74] "TimeBodyGyroscopeMagnitude.std.."                      
[75] "TimeBodyGyroscopeJerkMagnitude.std.."                  
[76] "FrequencyBodyAccelerometer.std...X"                    
[77] "FrequencyBodyAccelerometer.std...Y"                    
[78] "FrequencyBodyAccelerometer.std...Z"                    
[79] "FrequencyBodyAccelerometerJerk.std...X"                
[80] "FrequencyBodyAccelerometerJerk.std...Y"                
[81] "FrequencyBodyAccelerometerJerk.std...Z"                
[82] "FrequencyBodyGyroscope.std...X"                        
[83] "FrequencyBodyGyroscope.std...Y"                        
[84] "FrequencyBodyGyroscope.std...Z"                        
[85] "FrequencyBodyAccelerometerMagnitude.std.."             
[86] "FrequencyBodyBodyAccelerometerJerkMagnitude.std.."     
[87] "FrequencyBodyBodyGyroscopeMagnitude.std.."             
[88] "FrequencyBodyBodyGyroscopeJerkMagnitude.std.."

